### PR TITLE
Fix r 3 errors

### PR DESCRIPTION
**Pull request by mattsecrest**

### CODE REVIEW

**Comment by mattsecrest** [comment]
Fixes #34

**Comment by gowerc** [comment]
Should a unit test be added to show that the  HR value is not changing and is equal to the value set by the user ?

**Comment by mattsecrest** [comment]
@gowerc added a test case, lmk if you agree with the tests

**Comment by gowerc** [comment]
This all looks good to me, Only thing to add is that there is an additional `as.data.frame` in `utils.R` which should probably have the same change to it as well

**Review by gowerc — APPROVED** [review]

**Pull request merged**
